module.exports = [
  {
    "ID": "440",
    "Nama Trainee": "Sofia Grace Wu",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "House of Creanova",
    "Class": "Gladwell",
    "Branch": "TIMOR",
    "Total Gold/Periode": "890",
    "Junior/Youth": "Junior",
    "RANK/ID": "1"
  },
  {
    "ID": "70100078",
    "Nama Trainee": "Sakina Alima Regune Harahap",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Lt. General",
    "House": "House of Thenova",
    "Class": "Atlanta",
    "Branch": "TRITURA",
    "Total Gold/Periode": "1400",
    "Junior/Youth": "Youth",
    "RANK/ID": "1"
  },
  {
    "ID": "482",
    "Nama Trainee": "Reizo Kazuo Wong",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Havaria",
    "Class": "Grande (Thu 4-6 PM)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "830",
    "Junior/Youth": "Youth",
    "RANK/ID": "2"
  },
  {
    "ID": "70100153",
    "Nama Trainee": "Dareen Azel Matthew Sembiring",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "480",
    "Junior/Youth": "Junior",
    "RANK/ID": "4"
  },
  {
    "ID": "90100138",
    "Nama Trainee": "Vyon Wynter Huang",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Pearl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "710",
    "Junior/Youth": "Junior",
    "RANK/ID": "2"
  },
  {
    "ID": "90100020",
    "Nama Trainee": "Winston Hubert",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "House of Thenova",
    "Class": "Ruby",
    "Branch": "CEMARA",
    "Total Gold/Periode": "570",
    "Junior/Youth": "Youth",
    "RANK/ID": "4"
  },
  {
    "ID": "950",
    "Nama Trainee": "Audrey Madison Loewe",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "480",
    "Junior/Youth": "Junior",
    "RANK/ID": "4"
  },
  {
    "ID": "896",
    "Nama Trainee": "Nicolas Carlie Kuwira",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "House of Havaria",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "620",
    "Junior/Youth": "Youth",
    "RANK/ID": "3"
  },
  {
    "ID": "70100098",
    "Nama Trainee": "Erland Sohilida Laia",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "455",
    "Junior/Youth": "Junior",
    "RANK/ID": "8"
  },
  {
    "ID": "70100052",
    "Nama Trainee": "Darrel Hizkia Tambunan",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "530",
    "Junior/Youth": "Youth",
    "RANK/ID": "5"
  },
  {
    "ID": "90100005",
    "Nama Trainee": "Felynn Holy Richson",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Pearl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "545",
    "Junior/Youth": "Junior",
    "RANK/ID": "3"
  },
  {
    "ID": "90100206",
    "Nama Trainee": "Metta Louise ellen",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Beryl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "530",
    "Junior/Youth": "Youth",
    "RANK/ID": "5"
  },
  {
    "ID": "683",
    "Nama Trainee": "Stanley Ace Lorence",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Tracy (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "450",
    "Junior/Youth": "Junior",
    "RANK/ID": "9"
  },
  {
    "ID": "803",
    "Nama Trainee": "Lovea Fendy Kho",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Lt. General",
    "House": "House of Quorion",
    "Class": "Grande (Thu 4-6 PM)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "460",
    "Junior/Youth": "Youth",
    "RANK/ID": "8"
  },
  {
    "ID": "70100160",
    "Nama Trainee": "Jordan Noel Yap",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Denver",
    "Branch": "TRITURA",
    "Total Gold/Periode": "405",
    "Junior/Youth": "Junior",
    "RANK/ID": "11"
  },
  {
    "ID": "70100143",
    "Nama Trainee": "Kaleb Edgar Goel Hasugian",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Auckland",
    "Branch": "TRITURA",
    "Total Gold/Periode": "490",
    "Junior/Youth": "Youth",
    "RANK/ID": "7"
  },
  {
    "ID": "90100160",
    "Nama Trainee": "Klarissa Evania Buhari",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Reverion",
    "Class": "Pearl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "460",
    "Junior/Youth": "Junior",
    "RANK/ID": "6"
  },
  {
    "ID": "483",
    "Nama Trainee": "Jolie Charlotte Huang",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "",
    "Class": "Topaz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "440",
    "Junior/Youth": "Youth",
    "RANK/ID": "10"
  },
  {
    "ID": "1146",
    "Nama Trainee": "Charis Yafa Tobing",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Maxwell",
    "Branch": "TIMOR",
    "Total Gold/Periode": "430",
    "Junior/Youth": "Junior",
    "RANK/ID": "10"
  },
  {
    "ID": "745",
    "Nama Trainee": "Jesslyn",
    "Active/Expired": "Active",
    "Level": "General",
    "House": "House of Thenova",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "450",
    "Junior/Youth": "Youth",
    "RANK/ID": "9"
  },
  {
    "ID": "70100166",
    "Nama Trainee": "Farrin Rafania Shezan Lubis",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "360",
    "Junior/Youth": "Junior",
    "RANK/ID": "13"
  },
  {
    "ID": "70100155",
    "Nama Trainee": "Stella Aprilia Sianipar",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Reverion",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "430",
    "Junior/Youth": "Youth",
    "RANK/ID": "11"
  },
  {
    "ID": "90100232",
    "Nama Trainee": "Kathrine Chrestella",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "",
    "Class": "Pearl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "460",
    "Junior/Youth": "Junior",
    "RANK/ID": "6"
  },
  {
    "ID": "90100143",
    "Nama Trainee": "Jason Lewis Theo",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Azurite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "390",
    "Junior/Youth": "Youth",
    "RANK/ID": "14"
  },
  {
    "ID": "809",
    "Nama Trainee": "Emilia Niko Nyoman",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "320",
    "Junior/Youth": "Junior",
    "RANK/ID": "17"
  },
  {
    "ID": "48",
    "Nama Trainee": "Justin Maxwell",
    "Active/Expired": "Active (Grace Period)",
    "Level": "General",
    "House": "House of Havaria",
    "Class": "Millman (Sat 1-3)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "400",
    "Junior/Youth": "Youth",
    "RANK/ID": "12"
  },
  {
    "ID": "70100191",
    "Nama Trainee": "Yosihana Hutasoit",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "360",
    "Junior/Youth": "Junior",
    "RANK/ID": "13"
  },
  {
    "ID": "70100042",
    "Nama Trainee": "Jessica Sharon",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "360",
    "Junior/Youth": "Youth",
    "RANK/ID": "18"
  },
  {
    "ID": "90100190",
    "Nama Trainee": "Daphne Nathania Ang",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "370",
    "Junior/Youth": "Junior",
    "RANK/ID": "12"
  },
  {
    "ID": "90100153",
    "Nama Trainee": "Ethan Putra Gotama",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Ruby",
    "Branch": "CEMARA",
    "Total Gold/Periode": "390",
    "Junior/Youth": "Youth",
    "RANK/ID": "14"
  },
  {
    "ID": "999",
    "Nama Trainee": "Annabelle Grace Wu",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "310",
    "Junior/Youth": "Junior",
    "RANK/ID": "18"
  },
  {
    "ID": "716",
    "Nama Trainee": "Chloe Vallerie Jie",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Reverion",
    "Class": "Clinton (Fri 3-5)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "400",
    "Junior/Youth": "Youth",
    "RANK/ID": "12"
  },
  {
    "ID": "70100028",
    "Nama Trainee": "Elaine Gwen Lim",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Quorion",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "340",
    "Junior/Youth": "Junior",
    "RANK/ID": "15"
  },
  {
    "ID": "70100047",
    "Nama Trainee": "Keyzia Faiana Daulay",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Quorion",
    "Class": "Almeria",
    "Branch": "TRITURA",
    "Total Gold/Periode": "335",
    "Junior/Youth": "Youth",
    "RANK/ID": "19"
  },
  {
    "ID": "90100001",
    "Nama Trainee": "Rowan Maverick Ang",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Quartz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "310",
    "Junior/Youth": "Junior",
    "RANK/ID": "18"
  },
  {
    "ID": "90100127",
    "Nama Trainee": "Davin Bradford",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Azurite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "330",
    "Junior/Youth": "Youth",
    "RANK/ID": "20"
  },
  {
    "ID": "1040",
    "Nama Trainee": "Shane Anastasya Kristy Simangunsong",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Graham",
    "Branch": "TIMOR",
    "Total Gold/Periode": "310",
    "Junior/Youth": "Junior",
    "RANK/ID": "18"
  },
  {
    "ID": "1027",
    "Nama Trainee": "Elnino Jehanra Saragih",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Creanova",
    "Class": "Spielberg (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "390",
    "Junior/Youth": "Youth",
    "RANK/ID": "14"
  },
  {
    "ID": "70100023",
    "Nama Trainee": "Evonne Gwen Lim",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "330",
    "Junior/Youth": "Junior",
    "RANK/ID": "16"
  },
  {
    "ID": "70100046",
    "Nama Trainee": "Kirania Inara Azalea",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Almeria",
    "Branch": "TRITURA",
    "Total Gold/Periode": "310",
    "Junior/Youth": "Youth",
    "RANK/ID": "23"
  },
  {
    "ID": "90100183",
    "Nama Trainee": "Heinz victorio zhou",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Emerald",
    "Branch": "CEMARA",
    "Total Gold/Periode": "295",
    "Junior/Youth": "Junior",
    "RANK/ID": "21"
  },
  {
    "ID": "90100200",
    "Nama Trainee": "Galent hansen wuner",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Azurite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "320",
    "Junior/Youth": "Youth",
    "RANK/ID": "21"
  },
  {
    "ID": "955",
    "Nama Trainee": "Naomi Grace Edward",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Graham",
    "Branch": "TIMOR",
    "Total Gold/Periode": "290",
    "Junior/Youth": "Junior",
    "RANK/ID": "22"
  },
  {
    "ID": "872",
    "Nama Trainee": "Kenneth Samuel Lim",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Lt. Colonel",
    "House": "House of Creanova",
    "Class": "DaVinci",
    "Branch": "TIMOR",
    "Total Gold/Periode": "385",
    "Junior/Youth": "Youth",
    "RANK/ID": "17"
  },
  {
    "ID": "70100059",
    "Nama Trainee": "Rebecca Florencia Siregar",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Havaria",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Junior",
    "RANK/ID": "23"
  },
  {
    "ID": "70100134",
    "Nama Trainee": "Diandra Santika",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "300",
    "Junior/Youth": "Youth",
    "RANK/ID": "25"
  },
  {
    "ID": "255",
    "Nama Trainee": "Denzel Geraldo Wijaya",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Reverion",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Junior",
    "RANK/ID": "23"
  },
  {
    "ID": "90100097",
    "Nama Trainee": "Annabel Audriana",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Topaz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "310",
    "Junior/Youth": "Youth",
    "RANK/ID": "23"
  },
  {
    "ID": "763",
    "Nama Trainee": "Safira Reynia Hanum",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "270",
    "Junior/Youth": "Junior",
    "RANK/ID": "28"
  },
  {
    "ID": "767",
    "Nama Trainee": "Theodore Joachim Wihardjo",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Grande (Thu 4-6 PM)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "320",
    "Junior/Youth": "Youth",
    "RANK/ID": "21"
  },
  {
    "ID": "70100156",
    "Nama Trainee": "Tengku Muhammad Malik Al Fatih",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Junior",
    "RANK/ID": "23"
  },
  {
    "ID": "70100168",
    "Nama Trainee": "Mora Leticia Sinaga",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Creanova",
    "Class": "Almeria",
    "Branch": "TRITURA",
    "Total Gold/Periode": "260",
    "Junior/Youth": "Youth",
    "RANK/ID": "31"
  },
  {
    "ID": "90100055",
    "Nama Trainee": "Felicia Tham",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Quartz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Junior",
    "RANK/ID": "23"
  },
  {
    "ID": "90100080",
    "Nama Trainee": "Vanessa Cangie",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Topaz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "290",
    "Junior/Youth": "Youth",
    "RANK/ID": "27"
  },
  {
    "ID": "927",
    "Nama Trainee": "Richela Stanlay",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Dale (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "250",
    "Junior/Youth": "Junior",
    "RANK/ID": "32"
  },
  {
    "ID": "442",
    "Nama Trainee": "Beatrys Vanesa Moiras",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "House of Thenova",
    "Class": "Kiyosaki (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "300",
    "Junior/Youth": "Youth",
    "RANK/ID": "25"
  },
  {
    "ID": "70100174",
    "Nama Trainee": "Jerrick Onggoro Hakim",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Denver",
    "Branch": "TRITURA",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Junior",
    "RANK/ID": "23"
  },
  {
    "ID": "70100020",
    "Nama Trainee": "Diandra Ezra Nauli Simatupang",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "250",
    "Junior/Youth": "Youth",
    "RANK/ID": "32"
  },
  {
    "ID": "639",
    "Nama Trainee": "Bianca Olivia Ruslie",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "270",
    "Junior/Youth": "Junior",
    "RANK/ID": "28"
  },
  {
    "ID": "602",
    "Nama Trainee": "Alexandra Joan Micheline",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Creanova",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "265",
    "Junior/Youth": "Youth",
    "RANK/ID": "30"
  },
  {
    "ID": "857",
    "Nama Trainee": "Hogan Chan",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Tracy (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Junior",
    "RANK/ID": "35"
  },
  {
    "ID": "904",
    "Nama Trainee": "Callista Aurelia Tasma",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "290",
    "Junior/Youth": "Youth",
    "RANK/ID": "27"
  },
  {
    "ID": "70100090",
    "Nama Trainee": "Annisa Letizia Shanum",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Reverion",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "270",
    "Junior/Youth": "Junior",
    "RANK/ID": "28"
  },
  {
    "ID": "70100130",
    "Nama Trainee": "Muhammad Rafa Al Siena",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Auckland",
    "Branch": "TRITURA",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "90100081",
    "Nama Trainee": "Hayden Fredderick Halim",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "270",
    "Junior/Youth": "Junior",
    "RANK/ID": "28"
  },
  {
    "ID": "90100217",
    "Nama Trainee": "CHARLIE MIKKELSEN YAP",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Azurite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "784",
    "Nama Trainee": "Garrix Ardent Putra",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "220",
    "Junior/Youth": "Junior",
    "RANK/ID": "41"
  },
  {
    "ID": "1034",
    "Nama Trainee": "Cherryl Riquelme Potan",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Gandhi",
    "Branch": "TIMOR",
    "Total Gold/Periode": "280",
    "Junior/Youth": "Youth",
    "RANK/ID": "29"
  },
  {
    "ID": "70100122",
    "Nama Trainee": "Shadrina Azheema Lubis",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Creanova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "250",
    "Junior/Youth": "Junior",
    "RANK/ID": "32"
  },
  {
    "ID": "70100019",
    "Nama Trainee": "Andrea Tabitha Florencia Simatupang",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Creanova",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "230",
    "Junior/Youth": "Youth",
    "RANK/ID": "40"
  },
  {
    "ID": "90100044",
    "Nama Trainee": "Velove Alexa Winstan",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Creanova",
    "Class": "Amethyst",
    "Branch": "CEMARA",
    "Total Gold/Periode": "250",
    "Junior/Youth": "Junior",
    "RANK/ID": "32"
  },
  {
    "ID": "90100236",
    "Nama Trainee": "WINSTON XAVERIUS JUNIO",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Creanova",
    "Class": "Azurite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "995",
    "Nama Trainee": "Qori Putri Syahviah",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Gladwell",
    "Branch": "TIMOR",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Junior",
    "RANK/ID": "42"
  },
  {
    "ID": "285",
    "Nama Trainee": "Clairine Joshanley",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Clinton (Fri 3-5)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "70100186",
    "Nama Trainee": "Alvaro Gavriel Batara Sihotang",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "235",
    "Junior/Youth": "Junior",
    "RANK/ID": "37"
  },
  {
    "ID": "70100117",
    "Nama Trainee": "Akhdan Arief Athaya",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Asheville",
    "Branch": "TRITURA",
    "Total Gold/Periode": "230",
    "Junior/Youth": "Youth",
    "RANK/ID": "40"
  },
  {
    "ID": "90100004",
    "Nama Trainee": "Jeovenna Cangie",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Junior",
    "RANK/ID": "35"
  },
  {
    "ID": "90100068",
    "Nama Trainee": "Ixchel Lowell Tankiono",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Creanova",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "220",
    "Junior/Youth": "Youth",
    "RANK/ID": "43"
  },
  {
    "ID": "865",
    "Nama Trainee": "Victoria Yap",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Tracy (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Junior",
    "RANK/ID": "46"
  },
  {
    "ID": "741",
    "Nama Trainee": "Brayden Lisman",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Quorion",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "70100188",
    "Nama Trainee": "Latisya Naya Alamsyah Nasution",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "225",
    "Junior/Youth": "Junior",
    "RANK/ID": "39"
  },
  {
    "ID": "70100185",
    "Nama Trainee": "Alice Nathalie Brigitta",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Almeria",
    "Branch": "TRITURA",
    "Total Gold/Periode": "230",
    "Junior/Youth": "Youth",
    "RANK/ID": "40"
  },
  {
    "ID": "90100235",
    "Nama Trainee": "Hermione Emmilia Artjim",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "",
    "Class": "Emerald",
    "Branch": "CEMARA",
    "Total Gold/Periode": "230",
    "Junior/Youth": "Junior",
    "RANK/ID": "38"
  },
  {
    "ID": "90100002",
    "Nama Trainee": "Giselle Liandy",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Quorion",
    "Class": "Topaz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "989",
    "Nama Trainee": "Federico Fredelyn Jeoh",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Gladwell",
    "Branch": "TIMOR",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Junior",
    "RANK/ID": "46"
  },
  {
    "ID": "1077",
    "Nama Trainee": "Alqueenza Syifa Winona",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Clinton (Fri 3-5)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "240",
    "Junior/Youth": "Youth",
    "RANK/ID": "33"
  },
  {
    "ID": "70100159",
    "Nama Trainee": "Nadia Fathaniah Chandra",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Junior",
    "RANK/ID": "42"
  },
  {
    "ID": "70100135",
    "Nama Trainee": "Adib Nufal Wibowo",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Asheville",
    "Branch": "TRITURA",
    "Total Gold/Periode": "220",
    "Junior/Youth": "Youth",
    "RANK/ID": "43"
  },
  {
    "ID": "1081",
    "Nama Trainee": "Carlton Kho",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Pearl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "225",
    "Junior/Youth": "Junior",
    "RANK/ID": "39"
  },
  {
    "ID": "90100056",
    "Nama Trainee": "Thalissha Yeonan",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Ruby",
    "Branch": "CEMARA",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "751",
    "Nama Trainee": "Howie Chan",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Tracy (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "738",
    "Nama Trainee": "Adeline Njo",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "DaVinci",
    "Branch": "TIMOR",
    "Total Gold/Periode": "235",
    "Junior/Youth": "Youth",
    "RANK/ID": "39"
  },
  {
    "ID": "70100004",
    "Nama Trainee": "Maryam Shareen Anandifa",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Denver",
    "Branch": "TRITURA",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "70100121",
    "Nama Trainee": "Shane Anthony Jawson",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Auckland",
    "Branch": "TRITURA",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Youth",
    "RANK/ID": "47"
  },
  {
    "ID": "90100148",
    "Nama Trainee": "Kei Evander Buhari",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Reverion",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Junior",
    "RANK/ID": "42"
  },
  {
    "ID": "90100221",
    "Nama Trainee": "Ryan Aurelio Bustamin",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Youth",
    "RANK/ID": "58"
  },
  {
    "ID": "859",
    "Nama Trainee": "Clarissa Kho",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Graham",
    "Branch": "TIMOR",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "675",
    "Nama Trainee": "Maxen Zo Leon",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Gates (Sat 10-12)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "220",
    "Junior/Youth": "Youth",
    "RANK/ID": "43"
  },
  {
    "ID": "70100179",
    "Nama Trainee": "Doria Marchisia Giussevine Saragih",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "70100127",
    "Nama Trainee": "Gabriel Ihut Martuaro Sihombing",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Atlanta",
    "Branch": "TRITURA",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Youth",
    "RANK/ID": "47"
  },
  {
    "ID": "490",
    "Nama Trainee": "Shane Ferrucio Lim",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Havaria",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "202",
    "Junior/Youth": "Junior",
    "RANK/ID": "45"
  },
  {
    "ID": "90100022",
    "Nama Trainee": "Jeanice Wu",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Ruby",
    "Branch": "CEMARA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "988",
    "Nama Trainee": "Gavyn Wijaya",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Maxwell",
    "Branch": "TIMOR",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "1164",
    "Nama Trainee": "Felicia Ivana Silalahi",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Creanova",
    "Class": "DaVinci",
    "Branch": "TIMOR",
    "Total Gold/Periode": "220",
    "Junior/Youth": "Youth",
    "RANK/ID": "43"
  },
  {
    "ID": "70100193",
    "Nama Trainee": "Nadhira Ayria Verdian",
    "Active/Expired": "Active",
    "Level": "",
    "House": "House of Havaria",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Junior",
    "RANK/ID": "54"
  },
  {
    "ID": "70100136",
    "Nama Trainee": "Syakirah Khairani Jamilah",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Asheville",
    "Branch": "TRITURA",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Youth",
    "RANK/ID": "47"
  },
  {
    "ID": "90100070",
    "Nama Trainee": "Jack Austin Sia",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Quartz",
    "Branch": "CEMARA",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Junior",
    "RANK/ID": "48"
  },
  {
    "ID": "90100082",
    "Nama Trainee": "Tang En Xin",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Quorion",
    "Class": "Ruby",
    "Branch": "CEMARA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "726",
    "Nama Trainee": "Renzo Tanaka",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Graham",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Junior",
    "RANK/ID": "54"
  },
  {
    "ID": "680",
    "Nama Trainee": "Gracelyn Yap",
    "Active/Expired": "Active",
    "Level": "Lt. General",
    "House": "House of Quorion",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "210",
    "Junior/Youth": "Youth",
    "RANK/ID": "47"
  },
  {
    "ID": "70100064",
    "Nama Trainee": "Rachel Nathania Situmorang",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Creanova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "160",
    "Junior/Youth": "Junior",
    "RANK/ID": "63"
  },
  {
    "ID": "70100076",
    "Nama Trainee": "Marwa Alya Sakinah Rangkuti",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Thenova",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "90100108",
    "Nama Trainee": "Vergio Gavino Chaikoff",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Amethyst",
    "Branch": "CEMARA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Junior",
    "RANK/ID": "54"
  },
  {
    "ID": "868",
    "Nama Trainee": "Sergio Garcia Ang",
    "Active/Expired": "Active",
    "Level": "Lt. Colonel",
    "House": "House of Creanova",
    "Class": "Beryl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "160",
    "Junior/Youth": "Youth",
    "RANK/ID": "74"
  },
  {
    "ID": "942",
    "Nama Trainee": "Elaine Viandi",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Dale (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Junior",
    "RANK/ID": "54"
  },
  {
    "ID": "141",
    "Nama Trainee": "Russell William Tanner",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Quorion",
    "Class": "DaVinci",
    "Branch": "TIMOR",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "70100150",
    "Nama Trainee": "Nadhira Calista Purba",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "150",
    "Junior/Youth": "Junior",
    "RANK/ID": "67"
  },
  {
    "ID": "70100144",
    "Nama Trainee": "Faqih Fadhilah Wijaya",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Asheville",
    "Branch": "TRITURA",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "90100024",
    "Nama Trainee": "Welceline Charissa Tsjin",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "160",
    "Junior/Youth": "Junior",
    "RANK/ID": "63"
  },
  {
    "ID": "90100067",
    "Nama Trainee": "Victor Alexander Winstan",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Beryl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "160",
    "Junior/Youth": "Youth",
    "RANK/ID": "74"
  },
  {
    "ID": "1010",
    "Nama Trainee": "Gracielle Grace Ong",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Mandela",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Junior",
    "RANK/ID": "54"
  },
  {
    "ID": "1039",
    "Nama Trainee": "Naafa Maisyva Ginting",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Gandhi",
    "Branch": "TIMOR",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "70100180",
    "Nama Trainee": "Jevano Septarey Saragih",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "150",
    "Junior/Youth": "Junior",
    "RANK/ID": "67"
  },
  {
    "ID": "70100147",
    "Nama Trainee": "Faza Kiyana Azdah",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Athens",
    "Branch": "TRITURA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "90100116",
    "Nama Trainee": "Janessa Hofang",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "155",
    "Junior/Youth": "Junior",
    "RANK/ID": "66"
  },
  {
    "ID": "90100036",
    "Nama Trainee": "Carlos Ferdinand Putra",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "145",
    "Junior/Youth": "Youth",
    "RANK/ID": "82"
  },
  {
    "ID": "811",
    "Nama Trainee": "Arthur Floyd Salim",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Lincoln",
    "Branch": "TIMOR",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Junior",
    "RANK/ID": "59"
  },
  {
    "ID": "1161",
    "Nama Trainee": "Randa Miracle Boasly Sihombing",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "",
    "Class": "Galileo (Wed 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "200",
    "Junior/Youth": "Youth",
    "RANK/ID": "51"
  },
  {
    "ID": "70100123",
    "Nama Trainee": "Shafiqa Adeeva Lubis",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Eldorado",
    "Branch": "TRITURA",
    "Total Gold/Periode": "140",
    "Junior/Youth": "Junior",
    "RANK/ID": "75"
  },
  {
    "ID": "70100149",
    "Nama Trainee": "Jaeson Nathan Yap",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Auckland",
    "Branch": "TRITURA",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "90100010",
    "Nama Trainee": "Chloe Marjorie Wen",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Junior",
    "RANK/ID": "82"
  },
  {
    "ID": "329",
    "Nama Trainee": "Vrederick Benaricco Tanjaya",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Sapphire",
    "Branch": "CEMARA",
    "Total Gold/Periode": "140",
    "Junior/Youth": "Youth",
    "RANK/ID": "83"
  },
  {
    "ID": "1019",
    "Nama Trainee": "Louis Clinton Chai",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Mandela",
    "Branch": "TIMOR",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Junior",
    "RANK/ID": "59"
  },
  {
    "ID": "274",
    "Nama Trainee": "Candice Winardi Wong",
    "Active/Expired": "Active",
    "Level": "Colonel",
    "House": "House of Havaria",
    "Class": "Spielberg (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Youth",
    "RANK/ID": "58"
  },
  {
    "ID": "70100106",
    "Nama Trainee": "Dareen Davinci Ginting",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Denver",
    "Branch": "TRITURA",
    "Total Gold/Periode": "120",
    "Junior/Youth": "Junior",
    "RANK/ID": "91"
  },
  {
    "ID": "70100005",
    "Nama Trainee": "Lyvia Verlynn",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Colonel",
    "House": "House of Thenova",
    "Class": "Almeria",
    "Branch": "TRITURA",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Youth",
    "RANK/ID": "68"
  },
  {
    "ID": "90100011",
    "Nama Trainee": "Chloe Quisha Anggara",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Diamond",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Junior",
    "RANK/ID": "82"
  },
  {
    "ID": "90100204",
    "Nama Trainee": "Chloe Wong",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Havaria",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "135",
    "Junior/Youth": "Youth",
    "RANK/ID": "86"
  },
  {
    "ID": "1060",
    "Nama Trainee": "Zac Aldrich Mayor",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Dale (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Junior",
    "RANK/ID": "59"
  },
  {
    "ID": "1058",
    "Nama Trainee": "Gracia Tiffany Susanto",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Canfield",
    "Branch": "TIMOR",
    "Total Gold/Periode": "190",
    "Junior/Youth": "Youth",
    "RANK/ID": "58"
  },
  {
    "ID": "70100184",
    "Nama Trainee": "Atha Malik Chairmawan",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Denver",
    "Branch": "TRITURA",
    "Total Gold/Periode": "90",
    "Junior/Youth": "Junior",
    "RANK/ID": "106"
  },
  {
    "ID": "70100139",
    "Nama Trainee": "Daniella Demeintieva",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Auckland",
    "Branch": "TRITURA",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Youth",
    "RANK/ID": "68"
  },
  {
    "ID": "90100049",
    "Nama Trainee": "Harvey Susanto",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Havaria",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Junior",
    "RANK/ID": "82"
  },
  {
    "ID": "1020",
    "Nama Trainee": "Caren Axella Natania Lumbantoruan",
    "Active/Expired": "Active",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Beryl",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Youth",
    "RANK/ID": "87"
  },
  {
    "ID": "1079",
    "Nama Trainee": "Keigo Kusuno Soh",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Reverion",
    "Class": "Tracy (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Junior",
    "RANK/ID": "59"
  },
  {
    "ID": "1038",
    "Nama Trainee": "Devon Jau",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Creanova",
    "Class": "Canfield",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "70100176",
    "Nama Trainee": "Muhammad Asyam Haris Tanjung",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Cairo",
    "Branch": "TRITURA",
    "Total Gold/Periode": "80",
    "Junior/Youth": "Junior",
    "RANK/ID": "112"
  },
  {
    "ID": "70100158",
    "Nama Trainee": "Gracelyn Patricia",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Atlanta",
    "Branch": "TRITURA",
    "Total Gold/Periode": "170",
    "Junior/Youth": "Youth",
    "RANK/ID": "68"
  },
  {
    "ID": "90100060",
    "Nama Trainee": "Alfred Smaver Tanasal",
    "Active/Expired": "Active (Grace Period)",
    "Level": "Sergeant",
    "House": "House of Thenova",
    "Class": "Amber",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Junior",
    "RANK/ID": "82"
  },
  {
    "ID": "90100043",
    "Nama Trainee": "Valentino Owen Liu",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Jade",
    "Branch": "CEMARA",
    "Total Gold/Periode": "125",
    "Junior/Youth": "Youth",
    "RANK/ID": "93"
  },
  {
    "ID": "1139",
    "Nama Trainee": "Wilbert Wijaya",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Quorion",
    "Class": "Millman (Sat 1-3)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  },
  {
    "ID": "90100245",
    "Nama Trainee": "Mason Ivander Cahaya",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Alexandrite",
    "Branch": "CEMARA",
    "Total Gold/Periode": "130",
    "Junior/Youth": "Junior",
    "RANK/ID": "82"
  },
  {
    "ID": "1157",
    "Nama Trainee": "Gywen Stefanie Wiley",
    "Active/Expired": "Active",
    "Level": "Private",
    "House": "House of Thenova",
    "Class": "Ziglar (Sat 4-6)",
    "Branch": "TIMOR",
    "Total Gold/Periode": "180",
    "Junior/Youth": "Youth",
    "RANK/ID": "61"
  }
];
