const { pool } = require('./neonClient');

const traineesList = [
  { id: '27', name: 'Valerie Legolas Cen', status: 'Active' },
  { id: '45', name: 'Aaron Goldwin Semarak', status: 'Active (Grace Period)' },
  { id: '48', name: 'Justin Maxwell', status: 'Active' },
  { id: '49', name: 'Richmond Osyan Sudilan', status: 'Active' },
  { id: '50', name: 'Kenichi Zhou', status: 'Active' },
  { id: '51', name: 'Cedric Yago', status: 'Active (Grace Period)' },
  { id: '60', name: 'Sharleen Velicia Lim', status: 'Active' },
  { id: '64', name: 'Jillian Rusly', status: 'Active (Grace Period)' },
  { id: '125', name: 'Jayxen Maxwell', status: 'Active' },
  { id: '141', name: 'Russell William Tanner', status: 'Active' },
  { id: '149', name: 'Elaine Velicia', status: 'Active' },
  { id: '249', name: 'Emily Santo', status: 'Active' },
  { id: '274', name: 'Candice Winardi Wong', status: 'Active' },
  { id: '329', name: 'Vrederick Benaricco Tanjaya', status: 'Active' },
  { id: '333', name: 'Jasmine Yenarti', status: 'Active' },
  { id: '368', name: 'Felice Vallerie Angkasa', status: 'Active' },
  { id: '440', name: 'Sofia Grace Wu', status: 'Active' },
  { id: '528', name: 'Kiery Keionna Kie', status: 'Active (Grace Period)' },
  { id: '531', name: 'Max Chen', status: 'Active' },
  { id: '532', name: 'Yasmin Fadhila Azzakiyah', status: 'Active' },
  { id: '545', name: 'Brandon Chiang', status: 'Active' },
  { id: '255', name: 'Denzel Geraldo Wijaya', status: 'Active' },
  { id: '269', name: 'Fresia Victoria Chendry', status: 'Active' },
  { id: '285', name: 'Clairine Joshanley', status: 'Active' },
  { id: '301', name: 'Chloe Zhou', status: 'Active' },
  { id: '375', name: 'Darren Gabriel', status: 'Active' },
  { id: '429', name: 'Charrelle Anthony', status: 'Active' },
  { id: '442', name: 'Beatrys Vanesa Moiras', status: 'Active' },
  { id: '443', name: 'Candyce Valezka Moiras', status: 'Active' },
  { id: '482', name: 'Reizo Kazuo Wong', status: 'Active' },
  { id: '483', name: 'Jolie Huang', status: 'Active' },
  { id: '490', name: 'Shane Ferrucio Lim', status: 'Active' },
  { id: '548', name: 'Fiona Candiof', status: 'Active' },
  { id: '553', name: 'Florencia Hewi', status: 'Active' },
  { id: '566', name: 'Jollyn Felicia Wong', status: 'Active' },
  { id: '569', name: 'Josevin Carel H.', status: 'Active' },
  { id: '574', name: 'Brandon Tiojaya', status: 'Active' },
  { id: '575', name: 'Mandy Ellen Sanusi', status: 'Active' },
  { id: '580', name: 'Vivienne Zheng', status: 'Active' },
  { id: '581', name: 'Nicholas Zheng', status: 'Active' },
  { id: '582', name: 'Ethan Aldrich Lie', status: 'Active' },
  { id: '585', name: 'Harvey Wijaya', status: 'Active' },
  { id: '586', name: 'Annabella Wijaya', status: 'Active' },
  { id: '587', name: 'Enrico Victorian', status: 'Active' },
  { id: '601', name: 'Mikaella Hutteleigh Ng', status: 'Active' },
  { id: '602', name: 'Alexandra Joan Micheline', status: 'Active' },
  { id: '604', name: 'Hugo Viandi', status: 'Active' },
  { id: '613', name: 'Junior Auson Halim', status: 'Active' },
  { id: '614', name: 'Rayden Chiang', status: 'Active' },
  { id: '618', name: 'Yamin Yenardo', status: 'Active (Grace Period)' },
  { id: '621', name: 'Ufaira Tiandra Dalimunthe', status: 'Active (Grace Period)' },
  { id: '625', name: 'Audrey Hartono Lee', status: 'Active' },
  { id: '629', name: 'Joey Frederica Ang', status: 'Active' },
  { id: '631', name: 'Queency Joycelyn Yieginia', status: 'Active' },
  { id: '633', name: 'Fiona Jolys Chong', status: 'Active' },
  { id: '636', name: 'Zia Arafa Khairina', status: 'Active' },
  { id: '638', name: 'Chloe Olivia Ruslie', status: 'Active' },
  { id: '639', name: 'Bianca Olivia Ruslie', status: 'Active (Grace Period)' },
  { id: '651', name: 'Ashley Claire Lorence', status: 'Active' },
  { id: '654', name: 'Rayden Oh', status: 'Active' },
  { id: '665', name: 'Khoo Shu Han', status: 'Active' },
  { id: '670', name: 'Christian Anderson Lee', status: 'Active' },
  { id: '673', name: 'Nathan Immanuel Winanto', status: 'Active' },
  { id: '675', name: 'Maxen Zo Leon', status: 'Active' },
  { id: '676', name: 'Grace Alexandra', status: 'Active' },
  { id: '679', name: 'Fiorenza Eleanor Wijaya', status: 'Active' },
  { id: '680', name: 'Gracelyn Yap', status: 'Active' },
  { id: '683', name: 'Stanley Ace Lorence', status: 'Active' },
  { id: '686', name: 'Owen Linwood', status: 'Active' },
  { id: '704', name: 'Morgan Valentino Lowis', status: 'Active' },
  { id: '707', name: 'Samho Gunawan', status: 'Active' },
  { id: '709', name: 'Winston Lawrence', status: 'Active' },
  { id: '716', name: 'Chloe Vallerie Jie', status: 'Active' },
  { id: '717', name: 'Dmitri Meddef Njo', status: 'Active (Grace Period)' },
  { id: '719', name: 'Davar Aly Harahap', status: 'Active' },
  { id: '726', name: 'Renzo Tanaka', status: 'Active' },
  { id: '735', name: 'Kenward Melvern Djohan', status: 'Active' },
  { id: '736', name: 'Kendrick Melvern Djohan', status: 'Active' },
  { id: '738', name: 'Adeline Njo', status: 'Active' },
  { id: '739', name: 'Zoefiker Putera Ngadiman', status: 'Active' },
  { id: '740', name: 'Aubree Lisman', status: 'Active' },
  { id: '741', name: 'Brayden Lisman', status: 'Active' },
  { id: '745', name: 'Jesslyn', status: 'Active' },
  { id: '751', name: 'Howie Chan', status: 'Active' },
  { id: '754', name: 'Reagan Khei Subroto', status: 'Active' },
  { id: '759', name: 'Warren Emanuel', status: 'Active (Grace Period)' },
  { id: '761', name: 'Richelle Zheng', status: 'Active (Grace Period)' },
  { id: '763', name: 'Safira Reynia Hanum', status: 'Active' },
  { id: '767', name: 'Theodore Joachim Wihardjo', status: 'Active' },
  { id: '768', name: 'Josh Seravino Zhang', status: 'Active (Grace Period)' },
  { id: '779', name: 'Jayden Tarmidi', status: 'Active' },
  { id: '783', name: 'Evelynn Lee', status: 'Active' },
  { id: '784', name: 'Garrix Ardent Putra', status: 'Active' },
  { id: '785', name: 'Kelly Alyse Tanary', status: 'Active' },
  { id: '790', name: 'Hardey Moeldoko Law', status: 'Active' },
  { id: '801', name: 'Hillary Calista Tamado Panjaitan', status: 'Active' },
  { id: '803', name: 'Lovea Fendy Kho', status: 'Active' },
  { id: '806', name: 'Efrata Iskandar Liunardi', status: 'Active' },
  { id: '809', name: 'Emilia Niko Nyoman', status: 'Active' },
  { id: '811', name: 'Arthur Floyd Salim', status: 'Active' },
  { id: '819', name: 'Maria Jill Lumbantoruan', status: 'Active' },
  { id: '821', name: 'Vallerio', status: 'Active (Grace Period)' },
  { id: '822', name: 'Clarissa Olivia Anne Lammora Panjaitan', status: 'Active' },
  { id: '835', name: 'Finn Aldrich Luman', status: 'Active' },
  { id: '836', name: 'Kent Arthur Luman', status: 'Active' },
  { id: '837', name: 'Clairine Angela Indrajaya', status: 'Active' },
  { id: '838', name: 'Louis Harvey Soesanto', status: 'Active' },
  { id: '842', name: 'Ethan Moeritz', status: 'Active' },
  { id: '845', name: 'Wallace Evencio', status: 'Active' },
  { id: '850', name: 'Karin Destynsia', status: 'Active' },
  { id: '852', name: 'Cellistia Cangdiago', status: 'Active' },
  { id: '855', name: 'Cayden Louis Auwrich', status: 'Active' },
  { id: '857', name: 'Hogan Chan', status: 'Active' },
  { id: '858', name: 'Delmond Osyan Sudilan', status: 'Active' },
  { id: '859', name: 'Clarissa Kho', status: 'Active' },
  { id: '863', name: 'Bonita Gaudeti Sinaga', status: 'Active' },
  { id: '865', name: 'Victoria Yap', status: 'Active' },
  { id: '866', name: 'Carlsen Simen', status: 'Active' },
  { id: '867', name: 'Cherlyn Simen', status: 'Active' },
  { id: '868', name: 'Sergio Garcia Ang', status: 'Active' },
  { id: '872', name: 'Kenneth Samuel Lim', status: 'Active' },
  { id: '874', name: 'Muhammad Rafli Arkan', status: 'Active' },
  { id: '875', name: 'Clarissa Fredelyn Jeoh', status: 'Active' },
  { id: '876', name: 'Jacqueline Vallerie Chen', status: 'Active' },
  { id: '880', name: 'Joel Edward', status: 'Active' },
  { id: '883', name: 'Joanne Lynch', status: 'Active' },
  { id: '887', name: 'Filia Cielo Lim', status: 'Active' },
  { id: '889', name: 'Madelyn Odelia Lowis', status: 'Active' },
  { id: '896', name: 'Nicolas Carlie Kuwira', status: 'Active' },
  { id: '897', name: 'Valerie Ivana Chen', status: 'Active' },
  { id: '898', name: 'Ricson Stanlay', status: 'Active' },
  { id: '902', name: 'Malcolm', status: 'Active' },
  { id: '903', name: 'Harvey Oliver Lee', status: 'Active' },
  { id: '904', name: 'Callista Aurelia Tasma', status: 'Active' },
  { id: '909', name: 'Keona Jaileynn Lawrence', status: 'Active' },
  { id: '910', name: 'Michael Thamida', status: 'Active' },
  { id: '911', name: 'Meivellynn Thamida', status: 'Active' },
  { id: '913', name: 'Roselie Kirana Wijaya', status: 'Active' },
  { id: '914', name: 'Leia Kaytlyn Tioe', status: 'Active' },
  { id: '922', name: 'Victoria Cenata', status: 'Active' },
  { id: '927', name: 'Richela Stanlay', status: 'Active' },
  { id: '929', name: 'Trevor Hartono Lee', status: 'Active' },
  { id: '932', name: 'Olivia Tjoa', status: 'Active' },
  { id: '933', name: 'Ivy Jeane Chanella', status: 'Active' },
  { id: '935', name: 'Gisella Nyoto', status: 'Active (Grace Period)' },
  { id: '937', name: 'Jillian Claire Kuanrius', status: 'Active' },
  { id: '938', name: 'Reagan Nyoto', status: 'Active (Grace Period)' },
  { id: '939', name: 'Rexcaden Jazper Shu', status: 'Active (Grace Period)' },
  { id: '942', name: 'Elaine Viandi', status: 'Active' },
  { id: '945', name: 'Angeline Felice Theo', status: 'Active' },
  { id: '947', name: 'Nayyara Ayaskara Prakasita', status: 'Active' },
  { id: '948', name: 'Erick Winner Teo', status: 'Active' },
  { id: '950', name: 'Audrey Madison Loewe', status: 'Active' },
  { id: '951', name: 'Mavin Jericho Phen', status: 'Active' },
  { id: '955', name: 'Naomi Grace Edward', status: 'Active' },
  { id: '956', name: 'Aileen Sophie Kesuma', status: 'Active' },
  { id: '962', name: 'Ananda Putera Ngadiman', status: 'Active' },
  { id: '963', name: 'Yasmina Athirah Rifqi', status: 'Active' },
  { id: '964', name: 'Yazeed Abizar Rifqi', status: 'Active' },
  { id: '965', name: 'Modric Agusta Daruma', status: 'Active' },
  { id: '968', name: 'Lady Valery Sinambela', status: 'Active' },
  { id: '970', name: 'Annabela Himeko Winarta', status: 'Active' },
  { id: '980', name: 'Ezio Lim', status: 'Active' },
  { id: '981', name: 'Joey Milan Phen', status: 'Active' },
  { id: '982', name: 'Abigail Hazel Tamin', status: 'Active' },
  { id: '986', name: 'Jason Allen Tjoa', status: 'Active' },
  { id: '987', name: 'Caren Pandiago', status: 'Active' },
  { id: '988', name: 'Gavyn Wijaya', status: 'Active' },
  { id: '989', name: 'Federico Fredelyn Jeoh', status: 'Active' },
  { id: '990', name: 'Zason Riady Ko', status: 'Active' },
  { id: '991', name: 'Arya Kho', status: 'Active' },
  { id: '992', name: 'James Ananda Wijaya', status: 'Active' },
  { id: '995', name: 'Qori Putri Syahviah', status: 'Active' },
  { id: '996', name: 'Venesia Anggini Purba', status: 'Active' },
  { id: '997', name: 'Jovin Limcoln', status: 'Active' },
  { id: '998', name: 'Fedrick Wijaya', status: 'Active' },
  { id: '999', name: 'Annabelle Grace Wu', status: 'Active' },
  { id: '1003', name: 'Arthur Alexander Hakim', status: 'Active' },
  { id: '1007', name: 'Davina Grace Ong', status: 'Active' },
  { id: '1008', name: 'Sydney Princessa Lim', status: 'Active' },
  { id: '1009', name: 'Felicia Grace Ong', status: 'Active' },
  { id: '1010', name: 'Gracielle Grace Ong', status: 'Active' },
  { id: '1012', name: 'Clarence Aurelia Colim', status: 'Active (Grace Period)' },
  { id: '1015', name: 'Fransisca', status: 'Active' },
  { id: '1017', name: 'Harvardo Lovenzo Susanto', status: 'Active' },
  { id: '1019', name: 'Louis Clinton Chai', status: 'Active' },
  { id: '1020', name: 'Caren Axella Natania Lumbantoruan', status: 'Active' },
  { id: '1022', name: 'Efraim Lucas Dimitri', status: 'Active' },
  { id: '1023', name: 'Darryl Raynold Leowe', status: 'Active' },
  { id: '1024', name: 'Chloe Audrey Chen', status: 'Active' },
  { id: '1025', name: 'Hermione Lovely Susanto', status: 'Active' },
  { id: '1027', name: 'Elnino Jehanra Saragih', status: 'Active' },
  { id: '1028', name: 'Darren Winston', status: 'Active' },
  { id: '1029', name: 'Luna Antoinette Linne', status: 'Active' },
  { id: '1030', name: 'Valerie Rosalyn Yap', status: 'Active' },
  { id: '1031', name: 'Jacques Lewinsky', status: 'Active' },
  { id: '1033', name: 'Shelvina Howie', status: 'Active' },
  { id: '1034', name: 'Cherryl Riquelme Potan', status: 'Active' },
  { id: '1037', name: 'Caitlyn Allison Yaphen', status: 'Active' },
  { id: '1038', name: 'Devon Jau', status: 'Active' },
  { id: '1039', name: 'Naafa Maisyva Ginting', status: 'Active' },
  { id: '1040', name: 'Shane Anastasya Kristy Simangunsong', status: 'Active' },
  { id: '1041', name: 'Chloe Taydey', status: 'Active' },
  { id: '1043', name: 'Kenrich Thantio Yangderson', status: 'Active' },
  { id: '1044', name: 'Dominic Kie', status: 'Active' },
  { id: '1045', name: 'Silvario Soedidjo', status: 'Active' },
  { id: '1047', name: 'Jordan Tanutama', status: 'Active' },
  { id: '1049', name: 'Rafael Maximillian Sitorus', status: 'Active' },
  { id: '1050', name: 'Galang Roland Besch', status: 'Active' },
  { id: '1051', name: 'Timothy Anwi Panca', status: 'Active' },
  { id: '1053', name: 'Elaine Clemence Annabell', status: 'Active' },
  { id: '1056', name: 'Yeslin Yap', status: 'Active' },
  { id: '1057', name: 'Louis Xavier Leonardi', status: 'Active' },
  { id: '1058', name: 'Gracia Tiffany Susanto', status: 'Active' },
  { id: '1059', name: 'Meuthia Gadiza', status: 'Active' },
  { id: '1060', name: 'Zac Aldrich Mayor', status: 'Active' },
  { id: '1061', name: 'Kayden Skylar Sanso', status: 'Active' },
  { id: '1062', name: 'Queensya Lovely Reya', status: 'Active' },
  { id: '1065', name: 'Maxwell Louis Jaya', status: 'Active' },
  { id: '1066', name: 'Samuel Christopher Halim', status: 'Active (Grace Period)' },
  { id: '1067', name: 'Richester Casvio Liong', status: 'Active' },
  { id: '1071', name: 'Chloe Aurelia Ten', status: 'Active' },
  { id: '1072', name: 'Hazel Natalie Ten', status: 'Active' },
  { id: '1073', name: 'Scarlett Avery Ten', status: 'Active (Grace Period)' },
  { id: '1074', name: 'Ayska Najya Prakasita', status: 'Active' },
  { id: '1075', name: 'Bryan Michael Ng', status: 'Active' },
  { id: '1076', name: 'Brayden Matthew Ng', status: 'Active' },
  { id: '1077', name: 'Alqueenza Syifa Winona', status: 'Active' },
  { id: '1078', name: 'Ethan Kenny Daruma', status: 'Active' },
  { id: '1079', name: 'Keigo Kusuno Soh', status: 'Active' },
  { id: '1080', name: 'Reynara Amber Koiman', status: 'Active' },
  { id: '1081', name: 'Carlton Kho', status: 'Active' },
  { id: '1083', name: 'Gillian Alexa Pearl', status: 'Active (Grace Period)' },
  { id: '1084', name: 'Leonard Nyoto', status: 'Active (Grace Period)' },
  { id: '1085', name: 'Garent Nyoto', status: 'Active (Grace Period)' },
  { id: '1086', name: 'Kayden Ethan Zhou', status: 'Active' },
  { id: '1088', name: 'Alesha Sofia Andhika', status: 'Active' },
  { id: '1089', name: 'Jessica Jo', status: 'Active' },
  { id: '1090', name: 'Healey Tjoe', status: 'Active' },
  { id: '1093', name: 'Annastasia Hideko Winarta', status: 'Active' },
  { id: '1096', name: 'Maxwell Kenson Wibisono', status: 'Active' },
  { id: '1097', name: 'Reia Rose Winfield', status: 'Active' },
  { id: '1098', name: 'Naia Sydney Winfield', status: 'Active' },
  { id: '1101', name: 'Fredella Alexa Maranggi Siregar', status: 'Active' },
  { id: '1102', name: 'Adhyasta William Nugroho', status: 'Active' },
  { id: '1103', name: 'Nicholas Tjin', status: 'Active' },
  { id: '1104', name: 'Abbygael Mikaela Tangelyn', status: 'Active' },
  { id: '1105', name: 'Keiko Aiby Lim', status: 'Active' },
  { id: '1106', name: 'Vierra Cleevany Ryu', status: 'Active' },
  { id: '1111', name: 'Howie Leonard Wijaya', status: 'Active (Grace Period)' },
  { id: '1113', name: 'Joe Benedict Japto', status: 'Active' },
  { id: '1114', name: 'James Tjoa', status: 'Active (Grace Period)' },
  { id: '1115', name: 'Reagan Oliver Zhuang', status: 'Active' },
  { id: '1116', name: 'Kim Megumi', status: 'Active (Grace Period)' },
  { id: '1117', name: 'Claire Gabrielle Oscar', status: 'Active' },
  { id: '1119', name: 'Andrea Dimitri Ashraafi Lazzaroni', status: 'Active (Grace Period)' },
  { id: '1120', name: 'Reynand Wijaya', status: 'Active' },
  { id: '1121', name: 'Liam John Rickson', status: 'Active' },
  { id: '1122', name: 'Leeanne Jane Lim', status: 'Active' },
  { id: '1123', name: 'Joequinn Felysse Warsono', status: 'Active' },
  { id: '1124', name: 'Felicia Liangso', status: 'Active' },
  { id: '1125', name: 'Grace Anastasia Zeng', status: 'Active' },
  { id: '1127', name: 'Edric Luiz Ongka', status: 'Active' },
  { id: '1128', name: 'Lashira Awbinsriee Pane', status: 'Active' },
  { id: '1129', name: 'Stephanie Evelyn Luo', status: 'Active' },
  { id: '1130', name: 'Ethan Ray Maxwell', status: 'Active' },
  { id: '1131', name: 'Vinxiero Carrick Francoiz', status: 'Active' },
  { id: '1132', name: 'Nicole Lee', status: 'Active' },
  { id: '1133', name: 'Natalie Willeen Zhang', status: 'Active' },
  { id: '1134', name: 'Kent Nanda Daruma', status: 'Active' },
  { id: '1135', name: 'Cherysse Auryn Khobert', status: 'Active' },
  { id: '1137', name: 'Celine Angeline Yiandri', status: 'Active' },
  { id: '1138', name: 'Mike Louis Wijaya', status: 'Active' },
  { id: '1139', name: 'Wilbert Wijaya', status: 'Active' },
  { id: '1140', name: 'Keita Raelyn Deng', status: 'Active' },
  { id: '1141', name: 'Joyce Nathania Shen', status: 'Active (Grace Period)' },
  { id: '1142', name: 'Oscar Linwood', status: 'Active' },
  { id: '1143', name: 'Rico Alvaro Chandra', status: 'Active' },
  { id: '1144', name: 'Kayla Shilyn Gani', status: 'Active' },
  { id: '1145', name: 'Gallen Yuman King', status: 'Active' },
  { id: '1146', name: 'Charis Yafa Tobing', status: 'Active' },
  { id: '1147', name: 'Calista Kasih Aprilia Harahap', status: 'Active' },
  { id: '1148', name: 'Talysha Sri Nayla', status: 'Active' },
  { id: '1149', name: 'Arnold Alexander Hakim', status: 'Active' },
  { id: '1150', name: 'Kellyn Chandra', status: 'Active' },
  { id: '1151', name: 'Theona Zefanya Purba', status: 'Active' },
  { id: '1152', name: 'Javerson Joshua Tobing', status: 'Active' },
  { id: '1153', name: 'Philippe Benedict Zhuang', status: 'Active' },
  { id: '1154', name: 'Aca Raymond Tjemerlang', status: 'Active' },
  { id: '1155', name: 'Howard Winston Louis', status: 'Active' },
  { id: '1161', name: 'Randa Miracle Boasly Sihombing', status: 'Active' },
  { id: '1164', name: 'Felicia Ivana Silalahi', status: 'Active' },
  { id: '70100004', name: 'Maryam Shareen Anandifa', status: 'Active' },
  { id: '70100005', name: 'Lyvia Verlynn', status: 'Active' },
  { id: '70100019', name: 'Andrea Tabitha Florencia Simatupang', status: 'Active' },
  { id: '70100020', name: 'Diandra Ezra Nauli Simatupang', status: 'Active' },
  { id: '70100023', name: 'Evonne Gwen Lim', status: 'Active' },
  { id: '70100027', name: 'Daniel Goh', status: 'Active' },
  { id: '70100028', name: 'Elaine Gwen Lim', status: 'Active' },
  { id: '70100037', name: 'Abigail Rhea Lim', status: 'Active' },
  { id: '70100041', name: 'Raisha Adila Gunawan', status: 'Active' },
  { id: '70100042', name: 'Jessica Sharon', status: 'Active' },
  { id: '70100046', name: 'Kirania Inara Azalea', status: 'Active' },
  { id: '70100047', name: 'Keyzia Faiana Daulay', status: 'Active' },
  { id: '70100051', name: 'Enzo Howell', status: 'Active' },
  { id: '70100052', name: 'Darrel Hizkia Tambunan', status: 'Active' },
  { id: '70100059', name: 'Rebecca Florencia Siregar', status: 'Active' },
  { id: '70100060', name: 'Lincoln Blaine', status: 'Active' },
  { id: '70100061', name: 'Colleen Blaine', status: 'Active' },
  { id: '70100062', name: 'Nichole Hasan', status: 'Active' },
  { id: '70100063', name: 'Calysta Celorine Bakara', status: 'Active' },
  { id: '70100064', name: 'Rachel Nathania Situmorang', status: 'Active' },
  { id: '70100068', name: 'Radinka Agra Sitepu', status: 'Active' },
  { id: '70100070', name: 'Keysha Kania Ramaditya', status: 'Active' },
  { id: '70100071', name: 'Muhammad Al Khawarizmi Fairel', status: 'Active' },
  { id: '70100075', name: 'Maro Louis Dear Purba', status: 'Active' },
  { id: '70100076', name: 'Marwa Alya Sakinah Rangkuti', status: 'Active' },
  { id: '70100077', name: 'Aldiana Masha Lovelia Br Sembiring', status: 'Active' },
  { id: '70100078', name: 'Sakina Alima Regune Harahap', status: 'Active' },
  { id: '70100080', name: 'Dewi Syaahira Sabina Siregar', status: 'Active' },
  { id: '70100086', name: 'Maria Graciana Chica Purba', status: 'Active' },
  { id: '70100090', name: 'Annisa Letizia Shanum', status: 'Active' },
  { id: '70100098', name: 'Erland Sohilida Laia', status: 'Active' },
  { id: '70100102', name: 'Bryan Taslim', status: 'Active (Grace Period)' },
  { id: '70100106', name: 'Dareen Davinci Ginting', status: 'Active' },
  { id: '70100112', name: 'Fathi Arkan Wiyatmika', status: 'Active' },
  { id: '70100113', name: 'Jiselle Hartanto', status: 'Active' },
  { id: '70100117', name: 'Akhdan Arief Athaya', status: 'Active' },
  { id: '70100118', name: 'Cladys Nadine Frietania', status: 'Active (Grace Period)' },
  { id: '70100121', name: 'Shane Anthony Jawson', status: 'Active' },
  { id: '70100122', name: 'Shadrina Azheema Lubis', status: 'Active' },
  { id: '70100123', name: 'Shafiqa Adeeva Lubis', status: 'Active' },
  { id: '70100126', name: 'Berliando Lovely Sihombing', status: 'Active (Grace Period)' },
  { id: '70100127', name: 'Gabriel Ihut Martuaro Sihombing', status: 'Active' },
  { id: '70100128', name: 'Syia Kim', status: 'Active (Grace Period)' },
  { id: '70100130', name: 'Muhammad Rafa Al Siena', status: 'Active' },
  { id: '70100131', name: 'Clairine Bellvania Gavrila Ginting', status: 'Active (Grace Period)' },
  { id: '70100133', name: 'Lionel Maverick', status: 'Active' },
  { id: '70100134', name: 'Diandra Santika', status: 'Active' },
  { id: '70100135', name: 'Adib Nufal Wibowo', status: 'Active' },
  { id: '70100136', name: 'Syakirah Khairani Jamilah', status: 'Active' },
  { id: '70100139', name: 'Daniella Demeintieva', status: 'Active' },
  { id: '70100140', name: 'Gabriella Theofanny Putri Meliala', status: 'Active' },
  { id: '70100143', name: 'Kaleb Edgar Goel Hasugian', status: 'Active' },
  { id: '70100144', name: 'Faqih Fadhilah Wijaya', status: 'Active' },
  { id: '70100145', name: 'Hafiqa Raikhsa Karo Karo', status: 'Active' },
  { id: '70100146', name: 'Alexa Brianna Tambunan', status: 'Active' },
  { id: '70100147', name: 'Faza Kiyana Azdah', status: 'Active' },
  { id: '70100148', name: 'Davina Elisha Ginting', status: 'Active' },
  { id: '70100149', name: 'Jaeson Nathan Yap', status: 'Active' },
  { id: '70100150', name: 'Nadhira Calista Purba', status: 'Active' },
  { id: '70100151', name: 'Fakhira Idris Harahap', status: 'Active' },
  { id: '70100152', name: 'Abigail Carissa', status: 'Active' },
  { id: '70100153', name: 'Dareen Azel Matthew Sembiring', status: 'Active' },
  { id: '70100154', name: 'Ashera Natama Sitorus', status: 'Active' },
  { id: '70100155', name: 'Stella Aprilia Sianipar', status: 'Active' },
  { id: '70100156', name: 'Tengku Muhammad Malik Al Fatih', status: 'Active' },
  { id: '70100157', name: 'Faqhan Asshadiq Winata', status: 'Active' },
  { id: '70100158', name: 'Gracelyn Patricia', status: 'Active' },
  { id: '70100159', name: 'Nadia Fathaniah Chandra', status: 'Active' },
  { id: '70100160', name: 'Jordan Noel Yap', status: 'Active' },
  { id: '70100161', name: 'Khezya Queen Zareen Br Panggabean', status: 'Active' },
  { id: '70100162', name: 'Arya Satya', status: 'Active' },
  { id: '90100001', name: 'Rowan Maverick Ang', status: 'Active' },
  { id: '90100002', name: 'Giselle Liandy', status: 'Active' },
  { id: '90100004', name: 'Jeovenna Cangie', status: 'Active' },
  { id: '90100005', name: 'Felynn Holy Richson', status: 'Active' },
  { id: '90100007', name: 'Carrick Classico', status: 'Active' },
  { id: '90100010', name: 'Chloe Marjorie Wen', status: 'Active' },
  { id: '90100011', name: 'Chloe Quisha Anggara', status: 'Active' },
  { id: '90100013', name: 'Candice Julian Sakiwa', status: 'Active' },
  { id: '90100020', name: 'Winston Hubert', status: 'Active' },
  { id: '90100021', name: 'Aidan', status: 'Active' },
  { id: '90100022', name: 'Jeanice Wu', status: 'Active' },
  { id: '90100024', name: 'Welceline Charissa Tsjin', status: 'Active' },
  { id: '90100035', name: 'Carlen Edeline Br. Keliat', status: 'Active' },
  { id: '90100036', name: 'Carlos Ferdinand Putra', status: 'Active' },
  { id: '90100039', name: 'Reynard Alderich Guntur', status: 'Active' },
  { id: '90100042', name: 'Justin Nawi', status: 'Active' },
  { id: '90100043', name: 'Valentino Owen Liu', status: 'Active' },
  { id: '90100044', name: 'Velove Alexa Winstan', status: 'Active' },
  { id: '90100045', name: 'David Howard', status: 'Active' },
  { id: '90100046', name: 'Hugo Maximus Ling', status: 'Active' },
  { id: '90100047', name: 'Bryant Maximus Ling', status: 'Active' },
  { id: '90100049', name: 'Harvey Susanto', status: 'Active' },
  { id: '90100055', name: 'Felicia Tham', status: 'Active' },
  { id: '90100056', name: 'Thalissha Yeonan', status: 'Active' },
  { id: '90100060', name: 'Alfred Smaver Tanasal', status: 'Active' },
  { id: '90100061', name: 'Elaine Gabriella Chandella', status: 'Active' },
  { id: '90100064', name: 'Olson Arfayo', status: 'Active' },
  { id: '90100066', name: 'Celine Oubre', status: 'Active' },
  { id: '90100067', name: 'Victor Alexander Winstan', status: 'Active' },
  { id: '90100068', name: 'Ixchel Lowell Tankiono', status: 'Active' },
  { id: '90100070', name: 'Jack Austin Sia', status: 'Active' },
  { id: '90100074', name: 'Faulina Theresia Pangaribuan', status: 'Active' },
  { id: '90100075', name: 'Kingsley Alisson Tenang', status: 'Active' },
  { id: '90100079', name: 'Gracella Cangie', status: 'Active' },
  { id: '90100080', name: 'Vanessa Cangie', status: 'Active' },
  { id: '90100081', name: 'Hayden Fredderick Halim', status: 'Active' },
  { id: '90100082', name: 'Tang En Xin', status: 'Active' },
  { id: '90100083', name: 'Filbert Laithen', status: 'Active' },
  { id: '90100086', name: 'Eric Williarn', status: 'Active' },
  { id: '90100087', name: 'Finn Maxwell', status: 'Active' },
  { id: '90100088', name: 'Khairiy Raka Azizi Hermansyah', status: 'Active' },
  { id: '90100089', name: 'Alvyn Zhu', status: 'Active' },
  { id: '90100090', name: 'Alfarizy Raqila Hermansyah', status: 'Active' },
  { id: '90100093', name: 'Jesslyn Lee', status: 'Active' },
  { id: '90100094', name: 'Feliks Ananda Lee', status: 'Active' },
  { id: '90100097', name: 'Annabel Audriana', status: 'Active' },
  { id: '90100099', name: 'Rowan Tirta Lee', status: 'Active' },
  { id: '90100100', name: 'Jasmine Zhang', status: 'Active' },
  { id: '90100101', name: 'Jayden Zhang', status: 'Active' },
  { id: '90100102', name: 'Chloe Marche Khu', status: 'Active' },
  { id: '90100103', name: 'Claire Eugenia Khu', status: 'Active' },
  { id: '90100104', name: 'Hannah Sophia Salim', status: 'Active' },
  { id: '90100107', name: 'Stoffel Swandeez Angkasa', status: 'Active' },
  { id: '90100108', name: 'Vergio Gavino Chaikoff', status: 'Active' },
  { id: '90100109', name: 'Jolin Thianda', status: 'Active' },
  { id: '90100112', name: 'Richie Alvaro Tandinata', status: 'Active' },
  { id: '90100113', name: 'Reynard Shendior', status: 'Active' },
  { id: '90100114', name: 'Kate Elizabeth Huang', status: 'Active' },
  { id: '90100115', name: 'William Lauda', status: 'Active' },
  { id: '90100116', name: 'Janessa Hofang', status: 'Active' },
  { id: '90100117', name: 'Jarell Hofang', status: 'Active' },
  { id: '90100118', name: 'Jesslyn Hofang', status: 'Active' },
  { id: '90100120', name: 'Jocelyn Sydney', status: 'Active' },
  { id: '90100122', name: 'Tiffany Toh', status: 'Active' },
  { id: '90100123', name: 'Trevor Toh', status: 'Active' },
  { id: '90100127', name: 'Davin Bradford', status: 'Active' },
  { id: '90100128', name: 'Dustin Bradley', status: 'Active' },
  { id: '90100129', name: 'Jasmine Ryana Ngadimin', status: 'Active' },
  { id: '90100130', name: 'Maurice Claire Genevieve', status: 'Active' },
  { id: '90100131', name: 'Gillian Natalie Wilfred', status: 'Active' },
  { id: '90100132', name: 'Louis Adrian', status: 'Active' },
  { id: '90100133', name: 'Josh Andrew', status: 'Active' },
  { id: '90100134', name: 'Rodrick Stefano Halim', status: 'Active' },
  { id: '90100135', name: 'Rainie Lynn', status: 'Active' },
  { id: '90100136', name: 'Miho Qanitah Sihombing', status: 'Active' },
  { id: '90100137', name: 'Keiko Hanara Sihombing', status: 'Active (Grace Period)' },
  { id: '90100138', name: 'Vyon Wynter Huang', status: 'Active' },
  { id: '90100139', name: 'Mikayla Seline Wu', status: 'Active (Grace Period)' },
  { id: '90100140', name: 'Jadellyne Gretchenagatha Zhuotio', status: 'Active' },
  { id: '90100143', name: 'Jason Lewis Theo', status: 'Active' },
  { id: '90100144', name: 'Vincenzo', status: 'Active' },
  { id: '90100148', name: 'Kei Evander Buhari', status: 'Active' },
  { id: '90100153', name: 'Ethan Putra Gotama', status: 'Active' },
  { id: '90100154', name: 'Emmeline Aurelia Lie', status: 'Active' },
  { id: '90100155', name: 'Nathan Archie Gunawan', status: 'Active' },
  { id: '90100156', name: 'Nicole Anastasia', status: 'Active' },
  { id: '90100160', name: 'Klarissa Evania Buhari', status: 'Active' },
  { id: '90100161', name: 'Harvey Taufik', status: 'Active (Grace Period)' },
  { id: '90100163', name: 'Videline Gillian Chaikoff', status: 'Active (Grace Period)' },
  { id: '90100164', name: 'Jarred Eldridge Tantama', status: 'Active' },
  { id: '90100166', name: 'Reinz Stythan', status: 'Active' },
  { id: '90100167', name: 'Alicia Quinn chandranata', status: 'Active (Grace Period)' },
  { id: '90100168', name: 'Madelyn Henryetta Fang', status: 'Active' },
  { id: '90100169', name: 'Eleora Iskandar Liunardi', status: 'Active' },
  { id: '90100170', name: 'Viyona Gavriela Muis', status: 'Active' },
  { id: '90100171', name: 'Eileen Yui Chen', status: 'Active' },
  { id: '90100173', name: 'Jeneiro', status: 'Active' },
  { id: '90100174', name: 'Otto Valerino Lim', status: 'Active' },
  { id: '90100175', name: 'Jovan Leonard Lui', status: 'Active' },
  { id: '90100176', name: 'Rahma Nakita Afifah', status: 'Active' },
  { id: '90100177', name: 'Dominica Cherish Sheiramoth', status: 'Active' },
  { id: '90100178', name: 'MIRACLE HUANG', status: 'Active' },
  { id: '90100179', name: 'Emily moraine hakim', status: 'Active' },
  { id: '90100180', name: 'Jayden jiefferson', status: 'Active' },
  { id: '90100182', name: 'MAXWELL TENAR', status: 'Active' },
  { id: '90100183', name: 'Heinz victorio zhou', status: 'Active' },
  { id: '90100185', name: 'Natasha Clairine Wu', status: 'Active' },
  { id: '90100186', name: 'Samantha Clairine Wu', status: 'Active' },
  { id: '90100188', name: 'Rebecca kelly ashari', status: 'Active' },
  { id: '90100189', name: 'Abigail avery ashari', status: 'Active' },
  { id: '90100190', name: 'Daphne Nathania Ang', status: 'Active' },
  { id: '90100191', name: 'Bosco Lim', status: 'Active' },
  { id: '90100192', name: 'Jayden Jingga', status: 'Active' },
  { id: '90100193', name: 'Tyra Louise Tohnika', status: 'Active' },
  { id: '90100194', name: 'Tyler Howard Tohnika', status: 'Active (Grace Period)' },
  { id: '90100195', name: 'Sarah Oktorela Sitorus', status: 'Active' },
  { id: '90100196', name: 'Jordan Philip Wihono', status: 'Active' },
  { id: '90100197', name: 'Jeffrey Yap', status: 'Active' },
  { id: '90100198', name: 'Jordan Swiss Cliftan', status: 'Active' },
  { id: '90100200', name: 'Galent hansen wuner', status: 'Active' },
  { id: '90100206', name: 'Metta Louise ellen', status: 'Active' },
  { id: '90100208', name: 'Patricia', status: 'Active' },
  { id: '90100209', name: 'George', status: 'Active' },
  { id: '90100211', name: 'Callista Aurelia alven', status: 'Active' },
  { id: '90100214', name: 'Louis kendrick', status: 'Active' }
];

async function seed() {
  try {
    console.log('🔧 Creating table dashboard_trainne...');
    await pool.query(`
      CREATE TABLE IF NOT EXISTS dashboard_trainne (
        id VARCHAR(50) PRIMARY KEY,
        trainee_name VARCHAR(255) NOT NULL,
        status VARCHAR(100),
        program VARCHAR(255) DEFAULT NULL,
        class VARCHAR(255) DEFAULT NULL,
        level VARCHAR(255) DEFAULT NULL,
        membership_expiry VARCHAR(255) DEFAULT NULL,
        last_speaking_project VARCHAR(255) DEFAULT NULL,
        progress_ke_next_level VARCHAR(255) DEFAULT NULL,
        highlight_terbaru TEXT DEFAULT NULL,
        pengumuman TEXT DEFAULT NULL,
        weekly_report TEXT DEFAULT NULL,
        quarterly_report TEXT DEFAULT NULL,
        referral_code VARCHAR(255) DEFAULT NULL,
        gold_rank TEXT DEFAULT NULL,
        progress_video TEXT DEFAULT NULL,
        laporan_sebelumnya TEXT DEFAULT NULL,
        laporan_quarter_sebelumnya TEXT DEFAULT NULL,
        completed_speaking_project TEXT DEFAULT NULL
      );
    `);
    console.log('✅ Table dashboard_trainne created!');

    console.log('📥 Truncating old trainee data...');
    await pool.query('TRUNCATE TABLE dashboard_trainne CASCADE');

    console.log('📥 Seeding trainees...');
    for (const t of traineesList) {
      await pool.query(`
        INSERT INTO dashboard_trainne (id, trainee_name, status)
        VALUES ($1, $2, $3)
        ON CONFLICT (id) DO UPDATE SET
          trainee_name = EXCLUDED.trainee_name,
          status = EXCLUDED.status;
      `, [t.id, t.name, t.status]);
    }

    console.log(`🎉 Seeding complete! ${traineesList.length} trainees inserted.`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding dashboard_trainne:', error);
    process.exit(1);
  }
}

seed();
